server:
  port: 9596

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/showin_db
    username: postgres
    password: behdad2012


  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false

minio:
  bucket:
    name: showin
  default:
    folder: "/"
  access:
    name: minioadmin
    secret: minioadmin

  url: http://127.0.0.1:9000